name: 'Add Numbers Bash Action'
description: 'Adds two numbers using a bash script'
inputs:
  num1:
    description: 'First number'
    required: true
  num2:
    description: 'Second number'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        chmod +x ${{ github.action_path }}/add.sh
        ${{ github.action_path }}/add.sh "${{ inputs.num1 }}" "${{ inputs.num2 }}"
      shell: bash
