name: b11-workflow

on: push

jobs:
  run-addition:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, ubuntu-22.04 ]

    steps:
      - name: print message 
        run: echo "test"
          