name: b11-workflow

on: push

jobs:
  run-addition:
    runs-on: ubuntu-latest
    steps:
      - name: create a file and view it 
        run: |
            echo "test" > report.txt 
            cat report.txt 