name: b11-workflow 

on: push 

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print message for 3rd job 
        run: |
            sleep 10 
            echo "this is  first job" 

  second-job:
    runs-on: ubuntu-22.04
    steps:
      - name: print message for 2nd job
        run: |
          sleep 5  
          echo "this is 2nd job "
          

     

