name: b11-workflow 

on: push 

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: print message 
        run: |
              sleep 5
              echo "hello guys first stage " > test.txt 
              cat test.txt 

      - name: uploading the test.txt
        uses: actions/upload-artifact@v4
        with:
          name: test.txt   

             
  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: downloading test reports 
        uses: actions/download-artifact@v4
        with:
          name: test.txt  
          
      - name: view test reports 
        run: | 
          cat test.txt

