name: b11-workflow

on: push

jobs:
  run-addition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add 10 + 20 using bash custom action
        uses: ./.github/actions/add-numbers-bash
        with:
          num1: 10
          num2: 20
