name: b11-workflow

on: push

jobs:
  run-echo:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
      - name: Print test message
        run: echo "Running on ${{ matrix.os }} — test"
