name: b11-workflow 

on: push 

jobs:
  run-addition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add 5 + 10 using custom action
        uses: ./.github/actions/add-numbers
        with:
          num1: 10
          num2: 10
      

    
          

     

