name: b11-workflow 

on: push 

jobs:
  first-job:
    runs-on: [ prod , Linux]
    steps:
      - name: create a file 
        run: |
             echo "this is test reports" > report.txt 
             cat report.txt
      

    
          

     

